pre-release-commit-message = "chore: Update and release {{version}} on github"
tag-message = "{{tag_name}}"
tag-name = "{{prefix}}v{{version}}"
sign-tag = true
sign-commit = true
consolidate-commits = true
allow-branch = ["main"]
pre-release-replacements = [
    { file = "CHANGELOG.md", search = "## \\[Unreleased\\]", replace = "## [{{version}}] - {{date}}", exactly = 1 },
    { file = "CHANGELOG.md", search = "\\[Unreleased\\]:", replace = "[{{version}}]:", exactly = 1 },
    { file = "CHANGELOG.md", search = "\\.\\.\\.HEAD", replace = "...{{tag_name}}", exactly = 1 },
]
